### PR TITLE
Add CMAKE_PREFIX_PATH

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf this is still picking up something from AppVeyor:

```
-- Found OpenSSL:
optimized;C:/bld/libssh2_1553779135788/_h_env/Library/lib/libcrypto.lib;debug;
C:/OpenSSL-Win64/lib/VC/libeay32MDd.lib (found version "1.1.1a") 
```

**Comment by isuruf** [comment]
That's fine. The debug one is not used. To be sure, can you add `-DCMAKE_BUILD_TYPE=Release`

**Comment by ocefpaf** [comment]
> -DCMAKE_BUILD_TYPE=Release

Let's try that just to be sure. Thanks!

**Comment by ocefpaf** [comment]
Sorry, ended up merging #29 but they are virtually the same now. Thanks!

**Pull request closed without merging**
