### PR TITLE
Attempt to fix #7: busted pkg-config file

### LINKED ISSUE #7: Installed pkg-config file is broken
The `libssh2.pc` file installed with libssh2 is broken because the `libdir` variable that it defines somehow gets the prefix specified twice. If the prefix is `/a`, the first stanza of the file looks like:

```
prefix=/a
exec_prefix=${prefix}
libdir=${prefix}//a/lib
includedir=${prefix}/include
```

This means that downstream packages that attempt to link with libssh2 using the pkg-config information may fail, because they won't be able to pass the right `-L` flag to the linker. I've run into this problem in practice.

I believe that if `CMAKE_INSTALL_LIBDIR` is set to just `lib` it will automatically be made relative to `CMAKE_INSTALL_PREFIX`, and I suspect that will fix the problem.

### PR DESCRIPTION
**Pull request by pkgw**
This commit has some diagnostics that will be removed after I check that the fix works.

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
@pkgw , Thanks for tracking this down and fixing it! For documentation purposes, do you have any links to logs for problematic and fixed builds?

**Comment by pkgw** [comment]
The situation that I had was on a development rig where there aren't any logs, unfortunately.

**Comment by shadowwalkersb** [comment]
All right, then! I'll wait for TravisCI. Not sure, if I want to test it on another feedstock before merging.

**Comment by pkgw** [comment]
Travis finally ran.

**Pull request merged**
